# Generated by Django 4.2.7 on 2023-12-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='id',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
