# Generated by Django 4.2.7 on 2023-12-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0002_remove_timesheet_id_alter_timesheet_timesheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
