# Generated by Django 4.2.7 on 2023-11-30 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('credit_card', models.CharField(default='0000000000000000', max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^[0-9]+$')])),
                ('CVC', models.CharField(default='000', max_length=3, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^[0-9]+$')])),
                ('nameOnCard', models.CharField(default='John Doe', max_length=50)),
                ('validMonth', models.PositiveBigIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(12)])),
                ('ValidDay', models.PositiveBigIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(31)])),
            ],
        ),
    ]
