# Generated by Django 4.2.7 on 2023-11-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('credit_card', models.IntegerField()),
            ],
        ),
    ]
