# Generated by Django 4.2.7 on 2023-11-30 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='CVC',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='sale',
            name='ValidDay',
            field=models.IntegerField(default='1', validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='sale',
            name='nameOnCard',
            field=models.CharField(default='John Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='validMonth',
            field=models.IntegerField(default='1', validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credit_card',
            field=models.IntegerField(default='0000000000000000'),
        ),
    ]
