# Generated by Django 4.2.7 on 2023-11-30 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_sale_cvc_sale_validday_sale_nameoncard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='CVC',
            field=models.PositiveBigIntegerField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ValidDay',
            field=models.PositiveBigIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credit_card',
            field=models.PositiveBigIntegerField(default='0000000000000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='validMonth',
            field=models.PositiveBigIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
