# Generated by Django 4.2.7 on 2023-11-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="user_id", field=models.IntegerField(),
        ),
    ]
