# Generated by Django 4.2.7 on 2023-11-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
