# Generated by Django 4.2.7 on 2023-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.TextField(default='', max_length=20),
        ),
    ]
