# Generated by Django 4.2.7 on 2023-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('admin', 'Admin')], default='technician', max_length=30),
        ),
    ]
