# Generated by Django 4.2.7 on 2023-11-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.TextField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.TextField(default="", max_length=20),
        ),
    ]
