# Generated by Django 4.2.7 on 2023-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedBikes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='inventory.product')),
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('sale', models.ForeignKey(default=0, on_delete=models.SET(0), to='POS.sale')),
            ],
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('serial_number', models.IntegerField()),
                ('quantity_extra', models.IntegerField(default=0)),
                ('curr_amount_needed', models.IntegerField(default=0)),
                ('sale', models.ForeignKey(default=None, null=True, on_delete=models.SET(0), to='POS.sale')),
            ],
            bases=('inventory.product',),
        ),
    ]
