# Generated by Django 4.2.7 on 2023-11-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=50)),
                ('item_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('serial_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('curr_amount_needed', models.IntegerField(default=0)),
            ],
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='UsedBikes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='inventory.product')),
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('sale', models.ForeignKey(default=0, on_delete=models.SET(0), to='POS.sale')),
            ],
            bases=('inventory.product',),
        ),
    ]
