# Generated by Django 4.2.7 on 2023-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POS', '0001_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='open_jobs',
            field=models.ManyToManyField(default=None, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='parts',
            name='sale',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(0), to='POS.sale'),
        ),
    ]
