# Generated by Django 4.2.7 on 2023-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbikes',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
