# Generated by Django 4.2.7 on 2023-12-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='quantity',
            new_name='quantity_extra',
        ),
    ]
