# Generated by Django 4.2.7 on 2023-12-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_usedbikes_vehicle_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='inventory_product',
        ),
    ]
