# Generated by Django 4.2.7 on 2023-11-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='open_jobs',
            field=models.ManyToManyField(default=0, to='jobs.jobs'),
        ),
    ]
