# Generated by Django 4.2.7 on 2023-12-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='inventory_prod',
        ),
    ]
