# Generated by Django 4.2.7 on 2023-12-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_parts_quantity_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='open_jobs',
        ),
    ]
