# Generated by Django 4.2.7 on 2023-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('POS', '0001_initial'),
        ('inventory', '0004_alter_parts_open_jobs_alter_parts_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='open_jobs',
            field=models.ManyToManyField(default=None, null=True, to='jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='sale',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(0), to='POS.sale'),
        ),
    ]
