# Generated by Django 4.2.6 on 2023-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("POS", "0002_alter_sale_id"),
        ("inventory", "0005_alter_product_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parts",
            name="sale",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=models.SET(0),
                related_name="parts",
                to="POS.sale",
            ),
        ),
        migrations.AlterField(
            model_name="usedbikes",
            name="sale",
            field=models.ForeignKey(
                default=0,
                on_delete=models.SET(0),
                related_name="used_bikes",
                to="POS.sale",
            ),
        ),
    ]
