# Generated by Django 4.2.7 on 2023-12-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='usedbikes',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='usedbikes',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='usedbikes',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='usedbikes',
            name='year',
        ),
        migrations.AddField(
            model_name='usedbikes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
