# Generated by Django 4.2.7 on 2023-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.AddField(
            model_name='jobs',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
