# Generated by Django 4.2.7 on 2023-12-04 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0001_initial'),
        ('jobs', '0003_remove_jobs_id_jobs_completed_alter_jobs_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='POS.sale'),
        ),
    ]
