# Generated by Django 4.2.7 on 2023-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_assignee_alter_jobs_job_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
