# Generated by Django 4.2.7 on 2023-12-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_alter_jobs_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sale',
            field=models.ForeignKey(on_delete=models.SET(0), to='POS.sale'),
        ),
    ]
